### ISSUE TITLE
Certificate issue for docker pulling from the public repo

### ISSUE THREAD

**Issue by Maxsh** [gocd/docker-gocd-agent-dind#6] opened 2019-09-11 08:02 UTC
There is an issue with expired certificate for docker pulling in the agent container.

`[go] Task: /bin/bash -c "docker-compose build"took: 0.429sexited: 1`
`nginx uses an image, skipping`
`Building app`
`Step 1/22 : FROM php:7.2-fpm-alpine3.8`
`Service 'app' failed to build: Get https://registry-1.docker.io/v2/: x509: certificate has expired or is not yet valid`

Container is up in k8s Pod by Kubernetes Elastic agent.
According to the docker dind documentation, they should be in /certs directory
https://hub.docker.com/_/docker#tls

> Starting in 18.09+, the dind variants of this image will automatically generate TLS certificates in the directory specified by the DOCKER_TLS_CERTDIR environment variable.

Stack:
GoCD - **19.7.0** installing through helm to k8s cluster
Kubernetes Elastic Agent Plugin - **3.0.0-156**
  - based on **gocd/gocd-agent-docker-dind:v19.7.0**
  - In the agent container Docker version **19.03.1**, build 74b1e89e8a

Any thoughts?
Probably I need to generate certificates and map to the volume?

**Comment by arvindsv** [comment] 2019-09-11 16:13
Closing as a duplicate of https://github.com/gocd/kubernetes-elastic-agents/issues/138 for now. Can reopen if we learn it's not. Thank you!

**Closed as completed by arvindsv** 2019-09-11 16:13 UTC
